version: '2'
services:
  recatch-service:
    image: recatch-service:latest
    container_name: recatch-service
    ports:
      - "8082:8082"
    links: 
      - mongodb:mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports: 
      - "27017:27017"
    volumes:
     - /var/lib/mongo:/data/db
     - /var/log/mongodb:/var/log/mongodb
     - /etc/mongod.conf:/etc/mongod.conf.orig